package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

/**
 * ApartmentId generated by hbm2java
 */
public class ApartmentId implements java.io.Serializable {

	private String host;
	private String buildingNumber;
	private String street;
	private String flatNumber;
	private String city;

	public ApartmentId() {
	}

	public ApartmentId(String host, String buildingNumber, String street, String flatNumber, String city) {
		this.host = host;
		this.buildingNumber = buildingNumber;
		this.street = street;
		this.flatNumber = flatNumber;
		this.city = city;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getBuildingNumber() {
		return this.buildingNumber;
	}

	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getFlatNumber() {
		return this.flatNumber;
	}

	public void setFlatNumber(String flatNumber) {
		this.flatNumber = flatNumber;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApartmentId))
			return false;
		ApartmentId castOther = (ApartmentId) other;

		return ((this.getHost() == castOther.getHost()) || (this.getHost() != null && castOther.getHost() != null
				&& this.getHost().equals(castOther.getHost())))
				&& ((this.getBuildingNumber() == castOther.getBuildingNumber())
						|| (this.getBuildingNumber() != null && castOther.getBuildingNumber() != null
								&& this.getBuildingNumber().equals(castOther.getBuildingNumber())))
				&& ((this.getStreet() == castOther.getStreet()) || (this.getStreet() != null
						&& castOther.getStreet() != null && this.getStreet().equals(castOther.getStreet())))
				&& ((this.getFlatNumber() == castOther.getFlatNumber()) || (this.getFlatNumber() != null
						&& castOther.getFlatNumber() != null && this.getFlatNumber().equals(castOther.getFlatNumber())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
		result = 37 * result + (getBuildingNumber() == null ? 0 : this.getBuildingNumber().hashCode());
		result = 37 * result + (getStreet() == null ? 0 : this.getStreet().hashCode());
		result = 37 * result + (getFlatNumber() == null ? 0 : this.getFlatNumber().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		return result;
	}

}
