package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Apartment generated by hbm2java
 */
public class Apartment implements java.io.Serializable {

	private ApartmentId id;
	private User user;
	private double price;
	private int bedsAdult;
	private String type;
	private String name;
	private String description;
	private int bedsChild;
	private String country;
	private Set reservations = new HashSet(0);

	public Apartment() {
	}

	public Apartment(ApartmentId id, User user, double price, int bedsAdult, String name, String description,
			int bedsChild, String country) {
		this.id = id;
		this.user = user;
		this.price = price;
		this.bedsAdult = bedsAdult;
		this.name = name;
		this.description = description;
		this.bedsChild = bedsChild;
		this.country = country;
	}

	public Apartment(ApartmentId id, User user, double price, int bedsAdult, String type, String name,
			String description, int bedsChild, String country, Set reservations) {
		this.id = id;
		this.user = user;
		this.price = price;
		this.bedsAdult = bedsAdult;
		this.type = type;
		this.name = name;
		this.description = description;
		this.bedsChild = bedsChild;
		this.country = country;
		this.reservations = reservations;
	}

	public ApartmentId getId() {
		return this.id;
	}

	public void setId(ApartmentId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getBedsAdult() {
		return this.bedsAdult;
	}

	public void setBedsAdult(int bedsAdult) {
		this.bedsAdult = bedsAdult;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getBedsChild() {
		return this.bedsChild;
	}

	public void setBedsChild(int bedsChild) {
		this.bedsChild = bedsChild;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
