package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * MessageId generated by hbm2java
 */
public class MessageId implements java.io.Serializable {

	private String message;
	private Date date;
	private String sender;
	private String receiver;

	public MessageId() {
	}

	public MessageId(String message, Date date, String sender, String receiver) {
		this.message = message;
		this.date = date;
		this.sender = sender;
		this.receiver = receiver;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessageId))
			return false;
		MessageId castOther = (MessageId) other;

		return ((this.getMessage() == castOther.getMessage()) || (this.getMessage() != null
				&& castOther.getMessage() != null && this.getMessage().equals(castOther.getMessage())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getSender() == castOther.getSender()) || (this.getSender() != null
						&& castOther.getSender() != null && this.getSender().equals(castOther.getSender())))
				&& ((this.getReceiver() == castOther.getReceiver()) || (this.getReceiver() != null
						&& castOther.getReceiver() != null && this.getReceiver().equals(castOther.getReceiver())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getSender() == null ? 0 : this.getSender().hashCode());
		result = 37 * result + (getReceiver() == null ? 0 : this.getReceiver().hashCode());
		return result;
	}

}
