package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private MessageId id;
	private User userByReceiver;
	private User userBySender;
	private Byte isUnread;

	public Message() {
	}

	public Message(MessageId id, User userByReceiver, User userBySender) {
		this.id = id;
		this.userByReceiver = userByReceiver;
		this.userBySender = userBySender;
	}

	public Message(MessageId id, User userByReceiver, User userBySender, Byte isUnread) {
		this.id = id;
		this.userByReceiver = userByReceiver;
		this.userBySender = userBySender;
		this.isUnread = isUnread;
	}

	public MessageId getId() {
		return this.id;
	}

	public void setId(MessageId id) {
		this.id = id;
	}

	public User getUserByReceiver() {
		return this.userByReceiver;
	}

	public void setUserByReceiver(User userByReceiver) {
		this.userByReceiver = userByReceiver;
	}

	public User getUserBySender() {
		return this.userBySender;
	}

	public void setUserBySender(User userBySender) {
		this.userBySender = userBySender;
	}

	public Byte getIsUnread() {
		return this.isUnread;
	}

	public void setIsUnread(Byte isUnread) {
		this.isUnread = isUnread;
	}

}
