package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private ReservationId id;
	private Apartment apartment;
	private User user;
	private Date date;

	public Reservation() {
	}

	public Reservation(ReservationId id, Apartment apartment, User user) {
		this.id = id;
		this.apartment = apartment;
		this.user = user;
	}

	public Reservation(ReservationId id, Apartment apartment, User user, Date date) {
		this.id = id;
		this.apartment = apartment;
		this.user = user;
		this.date = date;
	}

	public ReservationId getId() {
		return this.id;
	}

	public void setId(ReservationId id) {
		this.id = id;
	}

	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
