package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

/**
 * ReservationId generated by hbm2java
 */
public class ReservationId implements java.io.Serializable {

	private String userEmail;
	private String apartmentHost;
	private String apartmentBuildingNumber;
	private String apartmentStreet;
	private String apartmentFlatNumber;
	private String apartmentCity;

	public ReservationId() {
	}

	public ReservationId(String userEmail, String apartmentHost, String apartmentBuildingNumber, String apartmentStreet,
			String apartmentFlatNumber, String apartmentCity) {
		this.userEmail = userEmail;
		this.apartmentHost = apartmentHost;
		this.apartmentBuildingNumber = apartmentBuildingNumber;
		this.apartmentStreet = apartmentStreet;
		this.apartmentFlatNumber = apartmentFlatNumber;
		this.apartmentCity = apartmentCity;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getApartmentHost() {
		return this.apartmentHost;
	}

	public void setApartmentHost(String apartmentHost) {
		this.apartmentHost = apartmentHost;
	}

	public String getApartmentBuildingNumber() {
		return this.apartmentBuildingNumber;
	}

	public void setApartmentBuildingNumber(String apartmentBuildingNumber) {
		this.apartmentBuildingNumber = apartmentBuildingNumber;
	}

	public String getApartmentStreet() {
		return this.apartmentStreet;
	}

	public void setApartmentStreet(String apartmentStreet) {
		this.apartmentStreet = apartmentStreet;
	}

	public String getApartmentFlatNumber() {
		return this.apartmentFlatNumber;
	}

	public void setApartmentFlatNumber(String apartmentFlatNumber) {
		this.apartmentFlatNumber = apartmentFlatNumber;
	}

	public String getApartmentCity() {
		return this.apartmentCity;
	}

	public void setApartmentCity(String apartmentCity) {
		this.apartmentCity = apartmentCity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservationId))
			return false;
		ReservationId castOther = (ReservationId) other;

		return ((this.getUserEmail() == castOther.getUserEmail()) || (this.getUserEmail() != null
				&& castOther.getUserEmail() != null && this.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getApartmentHost() == castOther.getApartmentHost())
						|| (this.getApartmentHost() != null && castOther.getApartmentHost() != null
								&& this.getApartmentHost().equals(castOther.getApartmentHost())))
				&& ((this.getApartmentBuildingNumber() == castOther.getApartmentBuildingNumber())
						|| (this.getApartmentBuildingNumber() != null && castOther.getApartmentBuildingNumber() != null
								&& this.getApartmentBuildingNumber().equals(castOther.getApartmentBuildingNumber())))
				&& ((this.getApartmentStreet() == castOther.getApartmentStreet())
						|| (this.getApartmentStreet() != null && castOther.getApartmentStreet() != null
								&& this.getApartmentStreet().equals(castOther.getApartmentStreet())))
				&& ((this.getApartmentFlatNumber() == castOther.getApartmentFlatNumber())
						|| (this.getApartmentFlatNumber() != null && castOther.getApartmentFlatNumber() != null
								&& this.getApartmentFlatNumber().equals(castOther.getApartmentFlatNumber())))
				&& ((this.getApartmentCity() == castOther.getApartmentCity())
						|| (this.getApartmentCity() != null && castOther.getApartmentCity() != null
								&& this.getApartmentCity().equals(castOther.getApartmentCity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37 * result + (getApartmentHost() == null ? 0 : this.getApartmentHost().hashCode());
		result = 37 * result
				+ (getApartmentBuildingNumber() == null ? 0 : this.getApartmentBuildingNumber().hashCode());
		result = 37 * result + (getApartmentStreet() == null ? 0 : this.getApartmentStreet().hashCode());
		result = 37 * result + (getApartmentFlatNumber() == null ? 0 : this.getApartmentFlatNumber().hashCode());
		result = 37 * result + (getApartmentCity() == null ? 0 : this.getApartmentCity().hashCode());
		return result;
	}

}
