package org.uc3m.ctftw.airbnb.model;
// Generated 05-Nov-2018 15:22:00 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String email;
	private String name;
	private String surname;
	private String password;
	private Set reservations = new HashSet(0);
	private Set messagesForReceiver = new HashSet(0);
	private Set apartments = new HashSet(0);
	private Set messagesForSender = new HashSet(0);

	public User() {
	}

	public User(String email) {
		this.email = email;
	}

	public User(String email, String name, String surname, String password, Set reservations, Set messagesForReceiver,
			Set apartments, Set messagesForSender) {
		this.email = email;
		this.name = name;
		this.surname = surname;
		this.password = password;
		this.reservations = reservations;
		this.messagesForReceiver = messagesForReceiver;
		this.apartments = apartments;
		this.messagesForSender = messagesForSender;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

	public Set getMessagesForReceiver() {
		return this.messagesForReceiver;
	}

	public void setMessagesForReceiver(Set messagesForReceiver) {
		this.messagesForReceiver = messagesForReceiver;
	}

	public Set getApartments() {
		return this.apartments;
	}

	public void setApartments(Set apartments) {
		this.apartments = apartments;
	}

	public Set getMessagesForSender() {
		return this.messagesForSender;
	}

	public void setMessagesForSender(Set messagesForSender) {
		this.messagesForSender = messagesForSender;
	}

}
